# Generated by Django 5.0.3 on 2024-03-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.URLField()),
                ('image', models.ImageField(upload_to='social_media_images')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
