# Generated by Django 5.0.3 on 2024-03-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='whatsapplink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_chat_link', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
