# Generated by Django 5.0.3 on 2024-03-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_whatsapplink_alter_socialmedialink_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapplink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='whatsapplink',
            name='text',
            field=models.CharField(default='WhatsApp Link', max_length=100),
        ),
    ]
