# Generated by Django 5.0.3 on 2024-03-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_whatsapplink_image_whatsapplink_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapplink',
            name='whatsapp_chat_link',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
