# Generated by Django 5.0.3 on 2024-03-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_whatsapplink_whatsapp_chat_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('number', models.CharField(default='WhatsApp Link', max_length=100)),
            ],
        ),
    ]
