# Generated by Django 5.0.3 on 2024-03-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='number',
            new_name='text',
        ),
    ]
