# Generated by Django 5.0.3 on 2024-03-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_number_mobile_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='lociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='WhatsApp Link', max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='whatsapplink',
            new_name='whatsappchat',
        ),
    ]
