# Generated by Django 5.0.3 on 2024-03-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_lociation_text_alter_mobile_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lociation',
            name='text',
            field=models.CharField(default='Location mobile', max_length=100),
        ),
    ]
