# Generated by Django 5.0.3 on 2024-03-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_lociation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='lociation',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lociation',
            name='text',
            field=models.CharField(default='Location Link', max_length=100),
        ),
    ]
