# Generated by Django 5.0.3 on 2024-03-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_lociation_mobile_alter_lociation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='lociation',
            name='map_link',
            field=models.URLField(blank=True),
        ),
    ]
