# Generated by Django 5.0.3 on 2024-03-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_lociation_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lociation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
