# Generated by Django 5.0.3 on 2024-03-21 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_lociation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedialink',
            name='text',
        ),
    ]
