# Generated by Django 5.0.3 on 2024-03-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_backgroundimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='background_images', verbose_name='Background Image'),
        ),
    ]
