# Generated by Django 5.0.3 on 2024-03-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_backgroundimage_image_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundImage',
        ),
    ]
