# Generated by Django 5.0.3 on 2024-03-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='title',
            field=models.CharField(default='Location Link', max_length=100),
        ),
    ]
