# Generated by Django 5.0.3 on 2024-03-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='description_en',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_en',
            field=models.CharField(default='Location Link', max_length=100),
        ),
        migrations.AddField(
            model_name='lociation',
            name='text_en',
            field=models.CharField(default='Location Link', max_length=100),
        ),
    ]
