# Generated by Django 5.0.3 on 2024-03-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_description_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(default='النص باللغه العربية'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title_en',
            field=models.CharField(default='العنوان باللغه الانجليزية', max_length=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='text',
            field=models.CharField(default='رقم الهاتف ', max_length=100),
        ),
        migrations.AlterField(
            model_name='whatsappchat',
            name='text',
            field=models.CharField(default='رقم الوتساب ', max_length=100),
        ),
    ]
