# Generated by Django 5.0.3 on 2024-03-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_description_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='description2',
            name='image_en',
            field=models.ImageField(blank=True, default='الصورة بالانجليزية', null=True, upload_to=''),
        ),
    ]
