# Generated by Django 5.0.3 on 2024-03-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_description2_image_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='locarb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(default='العنوان باللغة العربية', max_length=100)),
                ('title_en', models.CharField(default='العنوان باللغه الانجليزية', max_length=100)),
                ('href', models.URLField()),
            ],
        ),
    ]
