# Generated by Django 5.0.3 on 2024-03-26 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_locarb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='locarb',
            new_name='addlocarb',
        ),
    ]
